saucer:
	gcc -o saucer saucy.c -lpthread -lncurses
example:
	gcc -o example tanimate.c -lpthread -lncurses
run: clean saucer
	./saucer
clean:
	-rm -f *.o
	-rm -f
	-rm -f *~
	-rm -f *.out
	-rm -f saucer
	-rm -f example
